name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            svg
            svg:github-contribution-grid-snake.svg

      - name: Push snake
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          git add ./github-contribution-grid-snake.svg
          git commit -m "Update snake animation" || exit 0
          git push
